config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'

  resources :lists, only: %i[new create edit update destroy] do
    member do
      put :sort
    end
  end
  resources :todos, only: %i[new create edit update destroy] do
    member do
      put :sort
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  belongs_to :user
  has_many :todos, dependent: :destroy

  include RankedModel
  ranks :row_order
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
  belongs_to :list

  include RankedModel
  ranks :row_order, with_same: :list_id
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy
  has_many :todos, through: :lists
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index
    @lists = current_user.lists.rank(:row_order)
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :set_list, only: %i[edit update destroy]

  def new
    @list = List.new
  end

  def edit; end

  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.turbo_stream { flash[:notice] = 'List created successfully.' }
      else
        format.turbo_stream { flash[:alert] = 'List was not created.' }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.turbo_stream { flash[:notice] = 'List updated successfully.' }
      else
        format.turbo_stream { flash[:alert] = 'List was not updated.' }
      end
    end
  end

  def destroy
    @list.destroy!

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = 'List deleted successfully.' }
    end
  end

  def sort
    @list = List.find(params[:id])
    @list.update(row_order_position: params[:row_order_position])
    head :no_content
  end

  def list
    @todos = @list.todos.rank(:row_order)
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title, :user_id)
  end
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < ApplicationController
  before_action :set_todo, only: %i[edit update destroy]

  def new
    @todo = Todo.new
  end

  def edit; end

  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.turbo_stream { flash[:notice] = 'Todo created successfully.' }
      else
        format.turbo_stream { flash[:alert] = 'Todo was not created.' }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.turbo_stream { flash[:notice] = 'Todo updated successfully.' }
      else
        format.turbo_stream { flash[:alert] = 'Todo was not updated.' }
      end
    end
  end

  def destroy
    @todo.destroy!

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = 'Todo destroyed successfully.' }
    end
  end

  def sort
    @todo = Todo.find(params[:id])
    @todo.update(row_order_position: params[:row_order_position], list_id: params[:list_id])
    head :no_content
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :description, :completed, :due_date, :list_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
end

app/helpers/todos_helper.rb
# frozen_string_literal: true

module TodosHelper
end

app/views/dashboard/index.html.erb
<div class="w-full h-fit">

  <div>
    <ul id="lists" data-controller="sortable" class="grid grid-cols-3 gap-4">
        <% @lists.each do |list| %>
            <li data-sortable-update-url="<%= sort_list_path(list) %>">
                <%= render list %>
            </li>
        <% end %>
    </ul>
  </div>

  <div class="flex justify-center my-8">
    <%= button_to new_list_path, method: :get, params: { user_id: current_user.id }, data: { turbo_frame: 'modal' }, class: "add-list" do %>
      <%= heroicon('plus') %>
    <% end %>
  </div>

</div>

app/views/layouts/_alert.html.erb
<div data-controller="alert"
  data-transition-enter="transform ease-out duration-300 transition"
  data-transition-enter-start="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
  data-transition-enter-end="translate-y-0 opacity-100 sm:translate-x-0"
  data-transition-leave="transition ease-in duration-100"
  data-transition-leave-start="opacity-100"
  data-transition-leave-end="opacity-0"
  class="max-w-sm w-full bg-white shadow-lg rounded-lg pointer-events-auto ring-1 ring-black ring-opacity-5 overflow-hidden hidden">
  <div class="p-4">
    <div class="flex items-start">
      <div class="flex-shrink-0">
        <svg class="h-6 w-6 text-red-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      </div>
      <div class="ml-3 w-0 flex-1 pt-0.5">
        <p class="text-sm font-medium text-gray-900">Alert!</p>
        <p class="mt-1 text-sm text-gray-500"><%= alert %></p>
        <%# Need to clear flash[:alert] once displayed %>
        <% flash[:alert] = nil %>
      </div>
      <div class="ml-4 flex-shrink-0 flex">
        <button type="button" data-action="alert#close"  class="bg-white rounded-md inline-flex text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <span class="sr-only">Close</span>
          <!-- Heroicon name: solid/x -->
          <%= heroicon('x-mark') %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<div aria-live="assertive" class="fixed inset-0 flex items-end px-4 py-6 pointer-events-none sm:p-6 sm:items-start z-50">
    <div id="notifications" class="w-full flex flex-col items-center space-y-4 sm:items-end">
        <% if notice %>
            <%= render 'layouts/notice' %>
        <% end %>
        <% if alert %>
            <%= render 'layouts/alert' %>
        <% end %>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="my-5 flex justify-between">
    <div>
        <%= button_to new_list_path, method: :get, data: { turbo_frame: 'modal' }, class: "h-10 w-10 bg-green-600 rounded-full text-white" do %>
            <%= heroicon('plus') %>
        <% end %>
    </div>
    <h1 class="text-4xl font-medium tracking-wider text-white antialiased">notky.io</h1>
    <div class="flex gap-1">
        <%= button_to destroy_user_session_path, method: :delete, class: "h-10 w-10 text-white" do %>
            <%= heroicon('cog-6-tooth') %>
        <% end %>
        <%= button_to destroy_user_session_path, method: :delete, class: "h-10 w-10 text-white" do %>
            <%= heroicon('arrow-up-circle') %>
        <% end %>
    </div>
</div>

app/views/layouts/_notice.html.erb
<div data-controller="alert"
  data-transition-enter="transform ease-out duration-300 transition"
  data-transition-enter-start="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
  data-transition-enter-end="translate-y-0 opacity-100 sm:translate-x-0"
  data-transition-leave="transition ease-in duration-100"
  data-transition-leave-start="opacity-100"
  data-transition-leave-end="opacity-0"
  class="max-w-sm w-full bg-white shadow-lg rounded-lg pointer-events-auto ring-1 ring-black ring-opacity-5 overflow-hidden hidden">
  <div class="p-4">
    <div class="flex items-start">
      <div class="flex-shrink-0">
        <!-- Heroicon name: outline/check-circle -->
        <svg class="h-6 w-6 text-green-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      </div>
      <div class="ml-3 w-0 flex-1 pt-0.5">
        <p class="text-sm font-medium text-gray-900">Success!</p>
        <p class="mt-1 text-sm text-gray-500"><%= notice %></p>
        <%# Need to clear flash[:notice] once displayed %>
        <% flash[:notice] = nil %>
      </div>
      <div class="ml-4 flex-shrink-0 flex">
        <button type="button" data-action="alert#close"  class="bg-white rounded-md inline-flex text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <span class="sr-only">Close</span>
          <!-- Heroicon name: solid/x -->
          <%= heroicon('x-mark') %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>notky.io</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" %>
    <%= stylesheet_link_tag "https://ga.jspm.io/npm:flatpickr@4.6.9/dist/flatpickr.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class='container mx-auto mt-5 px-5 flex flex-col h-full'>
      <%= turbo_frame_tag 'modal' %>
      <%= render 'layouts/flash' %>
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, class: "contents") do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>" class="min-h-36 bg-yellow-200 bg-opacity-90 p-5 rounded shadow-lg w-80 my-4 relative mx-auto">
  <div class="flex items-center justify-between">
    <div>
      <%= button_to edit_list_path(list), method: :get, class: "h-5 w-5 text-sky-400" do %>
        <%= heroicon('pencil') %>
      <% end %>
    </div>

    <div>
      <%= button_to list_path(list), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-list" do %>
        <%= heroicon('trash') %>
      <% end %>
    </div>
  </div>
  
  <h3 class="text-lg text-center font-medium mb-4">
    <%= list.title %>
  </h3>

  <ul id="todos_<%= list.id %>" data-controller="sortable" data-sortable-group-value="todos" data-sortable-list-id="<%=list.id%>">
    <% list.todos.rank(:row_order).each do |todo| %>
      <li data-sortable-id="<%= todo.id %>" data-sortable-update-url="<%= sort_todo_path(todo) %>">
        <%= render todo %>
      </li>
    <% end %>
  </ul>

  <div class="flex justify-center mt-8">
    <%= button_to todos_path, params: { todo: { title: 'New todo', list_id: list.id } }, class: "add-todo" do %>
      <%= heroicon('plus') %>
    <% end %>
  </div>
</div>

app/views/lists/create.turbo_stream.erb
<%= turbo_stream.append("lists", partial: 'lists/list', locals: { list: @list }) %>

app/views/lists/destroy.turbo_stream.erb
<% if notice %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render 'layouts/notice' %>
  <% end %>
<% end %>
 
<% if alert %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render 'layouts/alert' %>
  <% end %>
<% end %>

<%= turbo_stream.remove("list_#{@list.id}") %>

app/views/lists/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing list</h1>

  <%= render "form", list: @list %>

  <%= link_to "Show this list", @list, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to lists", lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/lists/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Lists" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lists</h1>
    <%= link_to "New list", new_list_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="lists" class="min-w-full">
    <% @lists.each do |list| %>
      <%= render list %>
      <p>
        <%= link_to "Show this list", list, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal", 
                      turbo_modal_target: "modal", 
                      action: "turbo:submit-end->turbo-modal#submitEnd keyup@window->turbo-modal#closeWithKeyboard click@window->turbo-modal#closeBackground" }, 
                        class: "p-5 bg-yellow-200 bg-opacity-90 absolute z-10 top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 rounded-md w-96 break-words" do %>
              <%= render "form", list: @list %>
    <%= button_tag "Close", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white" %>
  <% end %>
<% end %>

app/views/lists/update.turbo_stream.erb
<% if notice %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render 'layouts/notice' %>
  <% end %>
<% end %>
 
<% if alert %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render 'layouts/alert' %>
  <% end %>
<% end %>

<%= turbo_stream.replace("list_#{@list.id}", partial: 'lists/list', locals: { list: @list }) %>

app/views/todos/_form.html.erb
<%= form_with model: todo, class: "contents" do |form| %>
  <%= turbo_frame_tag dom_id(todo, "title") do %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  <% end %>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>" class="flex flex-col gap-3 bg-opacity-100 hover:bg-yellow-300 p-2 rounded shadow-lg w-54 my-3" data-controller="todos">
  <div class="flex justify-between items-center">

    <%= form_with model: todo, class: "contents", data: { turbo_frame: dom_id(todo, "title") } do %>
      <%= turbo_frame_tag dom_id(todo, "title"), data: { controller: "inline-edit"} do %>
        <p data-todos-target="paragraph" class="py-3 pl-2 my-1 text-center text-sm font-medium">
          <%= link_to todo.title, edit_todo_path(todo) %>
        </p>
      <% end %>
    <% end %>

    <div class="flex items-center gap-3">
      <div>
        <%= form_with model: todo, class: "contents", data: { controller: "auto-submit" }, local: false do |form| %>
          <%= turbo_frame_tag dom_id(todo, "completed") do %>
            <%= form.check_box :completed, id: dom_id(todo, "completed"), data: { action: "auto-submit#submit click->todos#toggleCrossOut", "todos-target": "checkbox" } %>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>

  <div class="flex justify-between items-center">

    <div>
      <%= form_with model: todo, class: "contents" do |form| %>
        <%= form.date_field :due_date, class: "border-none", data: { controller: "flatpickr" } %>
      <% end %>
    </div>

    <%= button_to todo_path(todo), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-todo" do %>
      <%= heroicon('trash') %>
    <% end %>

  </div>

</div>

app/views/todos/create.turbo_stream.erb
<% if notice %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render 'layouts/notice' %>
  <% end %>
<% end %>
 
<% if alert %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render 'layouts/alert' %>
  <% end %>
<% end %>

<%= turbo_stream.append("todos_#{@todo.list.id}", partial: 'todos/todo', locals: { todo: @todo }) %>

app/views/todos/destroy.turbo_stream.erb
<% if notice %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render 'layouts/notice' %>
  <% end %>
<% end %>
 
<% if alert %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render 'layouts/alert' %>
  <% end %>
<% end %>

<%= turbo_stream.remove("todo_#{@todo.id}") %>

app/views/todos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to "Show this todo", @todo, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to todos", todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todos/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Todos" %>
  <h1 class="text-4xl font-medium text-center my-5 tracking-wider">Today</h1>

  <div class="grid grid-cols-3 gap-4">
    <% @todos.each do |todo| %>
      <%= render todo %>
    <% end %>
  </div>

  <%= link_to "New todo", new_todo_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
</div>

app/views/todos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to "Back to todos", todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todos/update.turbo_stream.erb
<% if notice %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render 'layouts/notice' %>
  <% end %>
<% end %>
 
<% if alert %>
  <%= turbo_stream.append 'notifications' do %>
    <%= render 'layouts/alert' %>
  <% end %>
<% end %>

<%= turbo_stream.replace("todo_#{@todo.id}", partial: 'todos/todo', locals: { todo: @todo }) %>